import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import {
  ActivityIndicator,
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { summarizeArticles } from "../services/aiService";
import { NewsArticle } from "../services/newsService";

const SummaryScreen = () => {
  const router = useRouter();
  const params = useLocalSearchParams<{ articles: string }>();

  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const generate = async () => {
      try {
        setLoading(true);
        setError(null);

        let articles: NewsArticle[] = [];
        if (params.articles) {
          articles = JSON.parse(params.articles) as NewsArticle[];
        }

        if (articles.length === 0) {
          throw new Error("No articles available to summarize.");
        }

        const result = await summarizeArticles(articles);
        setSummary(result);
      } catch (err: any) {
        setError(err.message || "Failed to generate summary.");
      } finally {
        setLoading(false);
      }
    };

    generate();
  }, [params.articles]);

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" />

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => router.back()}
        >
          <Ionicons name="arrow-back" size={22} color="#007AFF" />
        </TouchableOpacity>
        <View style={styles.headerCenter}>
          <Text style={styles.headerTitle}>AI Summary</Text>
          <Text style={styles.headerSubtitle}>Today&apos;s News Brief</Text>
        </View>
        <View style={styles.headerRight}>
          <Ionicons name="sparkles" size={22} color="#007AFF" />
        </View>
      </View>

      {/* Content */}
      {loading ? (
        <View style={styles.center}>
          <ActivityIndicator size="large" color="#007AFF" />
          <Text style={styles.loadingTitle}>Generating Summary</Text>
          <Text style={styles.loadingSubtitle}>
            AI is reading today&apos;s top stories...
          </Text>
        </View>
      ) : error ? (
        <View style={styles.center}>
          <Ionicons name="alert-circle-outline" size={56} color="#FF3B30" />
          <Text style={styles.errorTitle}>Something went wrong</Text>
          <Text style={styles.errorText}>{error}</Text>
          <TouchableOpacity
            style={styles.retryButton}
            onPress={() => router.back()}
          >
            <Text style={styles.retryButtonText}>Go Back</Text>
          </TouchableOpacity>
        </View>
      ) : (
        <ScrollView
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
        >
          <View style={styles.summaryCard}>
            <View style={styles.cardHeader}>
              <Ionicons name="newspaper-outline" size={20} color="#007AFF" />
              <Text style={styles.cardHeaderText}>AI Generated</Text>
            </View>
            <Text style={styles.summaryText}>{summary}</Text>
          </View>

          <View style={styles.disclaimer}>
            <Ionicons
              name="information-circle-outline"
              size={14}
              color="#999"
            />
            <Text style={styles.disclaimerText}>
              Summary generated by Gemini AI based on today&apos;s top
              headlines.
            </Text>
          </View>
        </ScrollView>
      )}
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f7fa",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e1e8ed",
  },
  backButton: {
    padding: 6,
    borderRadius: 20,
    backgroundColor: "#f0f7ff",
    borderWidth: 1.5,
    borderColor: "#d0e8ff",
  },
  headerCenter: {
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1a1a1a",
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#007AFF",
    fontWeight: "600",
    marginTop: 1,
  },
  headerRight: {
    padding: 6,
    borderRadius: 20,
    backgroundColor: "#f0f7ff",
    borderWidth: 1.5,
    borderColor: "#d0e8ff",
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
  },
  loadingTitle: {
    marginTop: 20,
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a1a",
  },
  loadingSubtitle: {
    marginTop: 8,
    fontSize: 14,
    color: "#666",
    textAlign: "center",
  },
  errorTitle: {
    marginTop: 16,
    fontSize: 20,
    fontWeight: "700",
    color: "#1a1a1a",
  },
  errorText: {
    marginTop: 8,
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    lineHeight: 20,
  },
  retryButton: {
    marginTop: 24,
    backgroundColor: "#007AFF",
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 25,
  },
  retryButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "600",
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  summaryCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  cardHeaderText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#007AFF",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  summaryText: {
    fontSize: 15,
    color: "#1a1a1a",
    lineHeight: 26,
  },
  disclaimer: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    marginTop: 16,
    paddingHorizontal: 4,
  },
  disclaimerText: {
    flex: 1,
    fontSize: 12,
    color: "#999",
    lineHeight: 18,
  },
});

export default SummaryScreen;
