import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import {
  ActivityIndicator,
  Pressable,
  ScrollView,
  Text,
  View,
} from "react-native";
import { summarizeArticles } from "@/src/services/aiService";
import { NewsArticle } from "@/src/services/newsService";

const SummaryScreen = () => {
  const router = useRouter();
  const params = useLocalSearchParams<{ articles: string }>();

  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const generate = async () => {
      try {
        setLoading(true);
        setError(null);

        let articles: NewsArticle[] = [];
        if (params.articles) {
          articles = JSON.parse(params.articles) as NewsArticle[];
        }

        if (articles.length === 0) {
          throw new Error("No articles available to summarize.");
        }

        const result = await summarizeArticles(articles);
        setSummary(result);
      } catch (err: any) {
        setError(err.message || "Failed to generate summary.");
      } finally {
        setLoading(false);
      }
    };

    generate();
  }, [params.articles]);

  if (loading) {
    return (
      <View
        style={{
          flex: 1,
          alignItems: "center",
          justifyContent: "center",
          gap: 16,
          backgroundColor: "#F2F2F7",
        }}
      >
        <View
          style={{
            width: 72,
            height: 72,
            borderRadius: 36,
            backgroundColor: "#EBF3FF",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <ActivityIndicator size="large" color="#007AFF" />
        </View>
        <Text style={{ fontSize: 18, fontWeight: "700", color: "#1C1C1E" }}>
          Generating Summary
        </Text>
        <Text style={{ fontSize: 14, color: "#8E8E93", textAlign: "center" }}>
          AI is reading today&apos;s top stories…
        </Text>
      </View>
    );
  }

  if (error) {
    return (
      <View
        style={{
          flex: 1,
          alignItems: "center",
          justifyContent: "center",
          gap: 14,
          padding: 32,
          backgroundColor: "#F2F2F7",
        }}
      >
        <Ionicons name="alert-circle-outline" size={56} color="#FF3B30" />
        <Text style={{ fontSize: 20, fontWeight: "700", color: "#1C1C1E" }}>
          Something went wrong
        </Text>
        <Text
          style={{
            fontSize: 15,
            color: "#636366",
            textAlign: "center",
            lineHeight: 22,
          }}
        >
          {error}
        </Text>
        <Pressable
          onPress={() => router.back()}
          style={{ backgroundColor: "#007AFF", paddingHorizontal: 32, paddingVertical: 12, borderRadius: 24, marginTop: 8 }}
        >
          <Text style={{ color: "#fff", fontWeight: "700", fontSize: 15 }}>Go Back</Text>
        </Pressable>
      </View>
    );
  }

  return (
    <ScrollView
      contentInsetAdjustmentBehavior="automatic"
      showsVerticalScrollIndicator={false}
      style={{ backgroundColor: "#F2F2F7" }}
      contentContainerStyle={{ padding: 16, gap: 14, paddingBottom: 40 }}
    >
      {/* Header badge */}
      <View
        style={{
          flexDirection: "row",
          alignItems: "center",
          gap: 8,
          padding: 14,
          backgroundColor: "#EBF3FF",
          borderRadius: 14,
          borderCurve: "continuous",
        }}
      >
        <Ionicons name="sparkles" size={18} color="#007AFF" />
        <View style={{ flex: 1 }}>
          <Text style={{ fontSize: 13, fontWeight: "700", color: "#007AFF" }}>
            AI Generated Summary
          </Text>
          <Text style={{ fontSize: 12, color: "#636366", marginTop: 1 }}>
            Powered by Gemini AI
          </Text>
        </View>
      </View>

      {/* Summary card */}
      <View
        style={{
          backgroundColor: "#FFFFFF",
          borderRadius: 18,
          borderCurve: "continuous",
          padding: 20,
          boxShadow: "0 2px 12px rgba(0,0,0,0.07)",
        }}
      >
        <Text
          selectable
          style={{
            fontSize: 16,
            color: "#1C1C1E",
            lineHeight: 26,
          }}
        >
          {summary}
        </Text>
      </View>

      {/* Disclaimer */}
      <View
        style={{
          flexDirection: "row",
          alignItems: "flex-start",
          gap: 6,
          paddingHorizontal: 4,
        }}
      >
        <Ionicons name="information-circle-outline" size={14} color="#8E8E93" style={{ marginTop: 1 }} />
        <Text style={{ flex: 1, fontSize: 12, color: "#8E8E93", lineHeight: 18 }}>
          Summary generated by Gemini AI based on today&apos;s top headlines. Always verify information from primary sources.
        </Text>
      </View>
    </ScrollView>
  );
};

export default SummaryScreen;
